live_config_reload = true

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/dark.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 750
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
y = 8

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001B"
key = "Escape"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mode = "~Search"
mods = "Command"

[shell]
args = ["--login", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
startup_mode = "Maximized"

[window.padding]
x = 3
y = 3
